### ISSUE TITLE
I have an error. How to fix?

### ISSUE THREAD

**Issue by misterjt** [dnemoga/Backbone.Schema#10]
```js

TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Function._.each._.forEach (/var/www/slivaev/data/node_modules/backbone.schema/node_modules/underscore/underscore.js:85:20)
    at handlers.(anonymous function)._.defaults.setter (/var/www/slivaev/data/node_modules/backbone.schema/dist/backbone.schema.js:456:23)
    at null.<anonymous> (/var/www/slivaev/data/node_modules/backbone.schema/node_modules/underscore/underscore.js:737:22)
    at /var/www/slivaev/data/node_modules/backbone.schema/dist/backbone.schema.js:115:42
    at Function._.each._.forEach (/var/www/slivaev/data/node_modules/backbone.schema/node_modules/underscore/underscore.js:87:22)
    at _.extend.set (/var/www/slivaev/data/node_modules/backbone.schema/dist/backbone.schema.js:107:19)
    at null.set (/var/www/slivaev/data/node_modules/backbone.schema/node_modules/underscore/underscore.js:737:22)
    at _.extend.refresh (/var/www/slivaev/data/node_modules/backbone.schema/dist/backbone.schema.js:400:24)
    at _.extend.define (/var/www/slivaev/data/node_modules/backbone.schema/dist/backbone.schema.js:383:18)
    at Model.extend.initialize (/var/www/slivaev/data/PeaceCMS/Models/Category.js:12:10)
    at Backbone.Model (/var/www/slivaev/data/node_modules/backbone-associations/node_modules/backbone/backbone.js:256:21)
    at child (/var/www/slivaev/data/node_modules/backbone-associations/node_modules/backbone/backbone.js:1541:41)
    at child (/var/www/slivaev/data/node_modules/backbone-associations/node_modules/backbone/backbone.js:1541:41)
    at new child (/var/www/slivaev/data/node_modules/backbone-associations/node_modules/backbone/backbone.js:1541:41)
    at _.extend._prepareModel (/var/www/slivaev/data/node_modules/backbone/backbone.js:916:19)
    at _.extend.set (/var/www/slivaev/data/node_modules/backbone/backbone.js:681:28)

```

This is my code

```js
initialize:function(){
		var schema=new Backbone.Schema(this);
		schema.define({
			'_id':{type:'number',getter: false},
			'parents':{array:'number',getter: false}
		});
	}

```

**Comment by alexpusch** [comment]
Old, inactive issue. Closing.
